// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ai_configs.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createAIConfig = `-- name: CreateAIConfig :one
INSERT INTO ai_configs (id, created_at, updated_at, name, model_id, system_prompt)
VALUES (
  gen_random_uuid(),
  NOW(),
  NOW(),
  $1,
  $2,
  $3
)
RETURNING id, created_at, updated_at, last_used_at, name, model_id, system_prompt
`

type CreateAIConfigParams struct {
	Name         string
	ModelID      uuid.UUID
	SystemPrompt sql.NullString
}

func (q *Queries) CreateAIConfig(ctx context.Context, arg CreateAIConfigParams) (AiConfig, error) {
	row := q.db.QueryRowContext(ctx, createAIConfig, arg.Name, arg.ModelID, arg.SystemPrompt)
	var i AiConfig
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.Name,
		&i.ModelID,
		&i.SystemPrompt,
	)
	return i, err
}

const deleteAIConfig = `-- name: DeleteAIConfig :exec
DELETE FROM ai_configs
WHERE id = $1
`

func (q *Queries) DeleteAIConfig(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAIConfig, id)
	return err
}

const getAIConfigByID = `-- name: GetAIConfigByID :one
SELECT id, created_at, updated_at, last_used_at, name, model_id, system_prompt FROM ai_configs
WHERE id = $1
`

func (q *Queries) GetAIConfigByID(ctx context.Context, id uuid.UUID) (AiConfig, error) {
	row := q.db.QueryRowContext(ctx, getAIConfigByID, id)
	var i AiConfig
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.Name,
		&i.ModelID,
		&i.SystemPrompt,
	)
	return i, err
}

const getAIConfigByName = `-- name: GetAIConfigByName :one
SELECT id, created_at, updated_at, last_used_at, name, model_id, system_prompt FROM ai_configs
WHERE name = $1
`

func (q *Queries) GetAIConfigByName(ctx context.Context, name string) (AiConfig, error) {
	row := q.db.QueryRowContext(ctx, getAIConfigByName, name)
	var i AiConfig
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.Name,
		&i.ModelID,
		&i.SystemPrompt,
	)
	return i, err
}

const listAIConfigs = `-- name: ListAIConfigs :many
SELECT id, created_at, updated_at, last_used_at, name, model_id, system_prompt FROM ai_configs
ORDER BY name
`

func (q *Queries) ListAIConfigs(ctx context.Context) ([]AiConfig, error) {
	rows, err := q.db.QueryContext(ctx, listAIConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiConfig
	for rows.Next() {
		var i AiConfig
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
			&i.Name,
			&i.ModelID,
			&i.SystemPrompt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAIConfigLastUsed = `-- name: UpdateAIConfigLastUsed :exec
UPDATE ai_configs
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateAIConfigLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateAIConfigLastUsed, id)
	return err
}

const updateAIConfigModel = `-- name: UpdateAIConfigModel :one
UPDATE ai_configs
SET
  model_id = $2,
  updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, last_used_at, name, model_id, system_prompt
`

type UpdateAIConfigModelParams struct {
	ID      uuid.UUID
	ModelID uuid.UUID
}

func (q *Queries) UpdateAIConfigModel(ctx context.Context, arg UpdateAIConfigModelParams) (AiConfig, error) {
	row := q.db.QueryRowContext(ctx, updateAIConfigModel, arg.ID, arg.ModelID)
	var i AiConfig
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.Name,
		&i.ModelID,
		&i.SystemPrompt,
	)
	return i, err
}

const updateAIConfigPrompt = `-- name: UpdateAIConfigPrompt :one
UPDATE ai_configs
SET
  system_prompt = $2,
  updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, last_used_at, name, model_id, system_prompt
`

type UpdateAIConfigPromptParams struct {
	ID           uuid.UUID
	SystemPrompt sql.NullString
}

func (q *Queries) UpdateAIConfigPrompt(ctx context.Context, arg UpdateAIConfigPromptParams) (AiConfig, error) {
	row := q.db.QueryRowContext(ctx, updateAIConfigPrompt, arg.ID, arg.SystemPrompt)
	var i AiConfig
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.Name,
		&i.ModelID,
		&i.SystemPrompt,
	)
	return i, err
}
