// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (id, created_at, updated_at, name)
VALUES (
  gen_random_uuid(),
  NOW(),
  NOW(),
  $1
)
RETURNING id, created_at, updated_at, last_used_at, name
`

func (q *Queries) CreateConversation(ctx context.Context, name sql.NullString) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, createConversation, name)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.Name,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversations
WHERE id = $1
`

func (q *Queries) DeleteConversation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteConversation, id)
	return err
}

const getConversation = `-- name: GetConversation :one
SELECT id, created_at, updated_at, last_used_at, name FROM conversations
WHERE id = $1
`

func (q *Queries) GetConversation(ctx context.Context, id uuid.UUID) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.Name,
	)
	return i, err
}

const listRecentConversations = `-- name: ListRecentConversations :many
SELECT id, created_at, updated_at, last_used_at, name FROM conversations
ORDER BY last_used_at DESC NULLS LAST
LIMIT $1
`

func (q *Queries) ListRecentConversations(ctx context.Context, limit int32) ([]Conversation, error) {
	rows, err := q.db.QueryContext(ctx, listRecentConversations, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversationLastUsed = `-- name: UpdateConversationLastUsed :exec
UPDATE conversations
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateConversationLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateConversationLastUsed, id)
	return err
}

const updateConversationName = `-- name: UpdateConversationName :one
UPDATE conversations
SET
  name = $2,
  updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, last_used_at, name
`

type UpdateConversationNameParams struct {
	ID   uuid.UUID
	Name sql.NullString
}

func (q *Queries) UpdateConversationName(ctx context.Context, arg UpdateConversationNameParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, updateConversationName, arg.ID, arg.Name)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.Name,
	)
	return i, err
}
