// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package database

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (id, created_at, updated_at, conversation_id, role, content)
VALUES (
  gen_random_uuid(),
  NOW(),
  NOW(),
  $1,
  $2,
  $3
)
RETURNING id, created_at, updated_at, conversation_id, user_id, role, content
`

type CreateMessageParams struct {
	ConversationID uuid.UUID
	Role           string
	Content        json.RawMessage
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage, arg.ConversationID, arg.Role, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConversationID,
		&i.UserID,
		&i.Role,
		&i.Content,
	)
	return i, err
}

const getMessagesByConversation = `-- name: GetMessagesByConversation :many
SELECT
  m.id, m.created_at, m.updated_at, m.conversation_id, m.user_id, m.role, m.content,
  u.id, u.created_at, u.updated_at, u.name
FROM messages m
LEFT JOIN users u ON m.user_id = u.id
WHERE m.conversation_id = $1
ORDER BY m.created_at ASC
`

type GetMessagesByConversationRow struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ConversationID uuid.UUID
	UserID         uuid.NullUUID
	Role           string
	Content        json.RawMessage
	User           User
}

func (q *Queries) GetMessagesByConversation(ctx context.Context, conversationID uuid.UUID) ([]GetMessagesByConversationRow, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesByConversationRow
	for rows.Next() {
		var i GetMessagesByConversationRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ConversationID,
			&i.UserID,
			&i.Role,
			&i.Content,
			&i.User.ID,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
