// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (id, created_at, updated_at, conversation_id, role, content)
VALUES (
  gen_random_uuid(),
  NOW(),
  NOW(),
  $1,
  $2,
  $3
)
RETURNING id, created_at, updated_at, conversation_id, role, content
`

type CreateMessageParams struct {
	ConversationID uuid.UUID
	Role           string
	Content        json.RawMessage
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage, arg.ConversationID, arg.Role, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConversationID,
		&i.Role,
		&i.Content,
	)
	return i, err
}

const getMessagesByConversation = `-- name: GetMessagesByConversation :many
SELECT id, created_at, updated_at, conversation_id, role, content FROM messages
WHERE conversation_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetMessagesByConversation(ctx context.Context, conversationID uuid.UUID) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ConversationID,
			&i.Role,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
