// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: models.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createModel = `-- name: CreateModel :one
INSERT INTO models (id, created_at, updated_at, provider_id, name, description)
VALUES (
  gen_random_uuid(),
  NOW(),
  NOW(),
  $1,
  $2,
  $3
)
RETURNING id, created_at, updated_at, provider_id, name, description
`

type CreateModelParams struct {
	ProviderID  uuid.UUID
	Name        string
	Description sql.NullString
}

func (q *Queries) CreateModel(ctx context.Context, arg CreateModelParams) (Model, error) {
	row := q.db.QueryRowContext(ctx, createModel, arg.ProviderID, arg.Name, arg.Description)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderID,
		&i.Name,
		&i.Description,
	)
	return i, err
}

const deleteModel = `-- name: DeleteModel :exec
DELETE FROM models
WHERE id = $1
`

func (q *Queries) DeleteModel(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteModel, id)
	return err
}

const getModelByID = `-- name: GetModelByID :one
SELECT id, created_at, updated_at, provider_id, name, description FROM models
WHERE id = $1
`

func (q *Queries) GetModelByID(ctx context.Context, id uuid.UUID) (Model, error) {
	row := q.db.QueryRowContext(ctx, getModelByID, id)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderID,
		&i.Name,
		&i.Description,
	)
	return i, err
}

const getModelByName = `-- name: GetModelByName :one
SELECT id, created_at, updated_at, provider_id, name, description FROM models
WHERE name = $1
`

func (q *Queries) GetModelByName(ctx context.Context, name string) (Model, error) {
	row := q.db.QueryRowContext(ctx, getModelByName, name)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderID,
		&i.Name,
		&i.Description,
	)
	return i, err
}

const listModels = `-- name: ListModels :many
SELECT id, created_at, updated_at, provider_id, name, description FROM models
ORDER BY name
`

func (q *Queries) ListModels(ctx context.Context) ([]Model, error) {
	rows, err := q.db.QueryContext(ctx, listModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Model
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProviderID,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelsByProvider = `-- name: ListModelsByProvider :many
SELECT id, created_at, updated_at, provider_id, name, description FROM models
WHERE provider_id = $1
ORDER BY name
`

func (q *Queries) ListModelsByProvider(ctx context.Context, providerID uuid.UUID) ([]Model, error) {
	rows, err := q.db.QueryContext(ctx, listModelsByProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Model
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProviderID,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
