// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type AiConfig struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	LastUsedAt   sql.NullTime
	Name         string
	ModelID      uuid.UUID
	SystemPrompt sql.NullString
}

type Conversation struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	LastUsedAt sql.NullTime
	Name       sql.NullString
}

type Message struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ConversationID uuid.UUID
	Role           string
	Content        json.RawMessage
}

type Model struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ProviderID  uuid.UUID
	Name        string
	Description sql.NullString
}

type Provider struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}
