// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: providers.sql

package database

import (
	"context"
)

const createProvider = `-- name: CreateProvider :one
INSERT INTO providers (id, created_at, updated_at, name)
VALUES (
  gen_random_uuid(),
  NOW(),
  NOW(),
  $1
)
RETURNING id, created_at, updated_at, name
`

func (q *Queries) CreateProvider(ctx context.Context, name string) (Provider, error) {
	row := q.db.QueryRowContext(ctx, createProvider, name)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const deleteProvider = `-- name: DeleteProvider :exec
DELETE FROM providers
WHERE name = $1
`

func (q *Queries) DeleteProvider(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteProvider, name)
	return err
}

const getProvider = `-- name: GetProvider :one
SELECT id, created_at, updated_at, name FROM providers
WHERE name = $1
`

func (q *Queries) GetProvider(ctx context.Context, name string) (Provider, error) {
	row := q.db.QueryRowContext(ctx, getProvider, name)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const listProviders = `-- name: ListProviders :many
SELECT id, created_at, updated_at, name FROM providers
ORDER BY name
`

func (q *Queries) ListProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.QueryContext(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Provider
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
