// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: io.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IOService_SendMessage_FullMethodName        = "/io.IOService/SendMessage"
	IOService_StoreMessage_FullMethodName       = "/io.IOService/StoreMessage"
	IOService_ListConversations_FullMethodName  = "/io.IOService/ListConversations"
	IOService_LoadConversation_FullMethodName   = "/io.IOService/LoadConversation"
	IOService_DeleteConversation_FullMethodName = "/io.IOService/DeleteConversation"
	IOService_ListAIConfigs_FullMethodName      = "/io.IOService/ListAIConfigs"
	IOService_SwitchAIConfig_FullMethodName     = "/io.IOService/SwitchAIConfig"
	IOService_ListProviders_FullMethodName      = "/io.IOService/ListProviders"
)

// IOServiceClient is the client API for IOService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The main service
type IOServiceClient interface {
	// Send a message and get AI response
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	// Send message to backend only for storage
	StoreMessage(ctx context.Context, in *StoreMessageRequest, opts ...grpc.CallOption) (*StoreMessageResponse, error)
	// Conversation management
	ListConversations(ctx context.Context, in *ListConversationsRequest, opts ...grpc.CallOption) (*ListConversationsResponse, error)
	LoadConversation(ctx context.Context, in *LoadConversationRequest, opts ...grpc.CallOption) (*LoadConversationResponse, error)
	DeleteConversation(ctx context.Context, in *DeleteConversationRequest, opts ...grpc.CallOption) (*DeleteConversationResponse, error)
	// AI Config management
	ListAIConfigs(ctx context.Context, in *ListAIConfigsRequest, opts ...grpc.CallOption) (*ListAIConfigsResponse, error)
	SwitchAIConfig(ctx context.Context, in *SwitchAIConfigRequest, opts ...grpc.CallOption) (*SwitchAIConfigResponse, error)
	// Provider management
	ListProviders(ctx context.Context, in *ListProvidersRequest, opts ...grpc.CallOption) (*ListProvidersResponse, error)
}

type iOServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIOServiceClient(cc grpc.ClientConnInterface) IOServiceClient {
	return &iOServiceClient{cc}
}

func (c *iOServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, IOService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iOServiceClient) StoreMessage(ctx context.Context, in *StoreMessageRequest, opts ...grpc.CallOption) (*StoreMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreMessageResponse)
	err := c.cc.Invoke(ctx, IOService_StoreMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iOServiceClient) ListConversations(ctx context.Context, in *ListConversationsRequest, opts ...grpc.CallOption) (*ListConversationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConversationsResponse)
	err := c.cc.Invoke(ctx, IOService_ListConversations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iOServiceClient) LoadConversation(ctx context.Context, in *LoadConversationRequest, opts ...grpc.CallOption) (*LoadConversationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadConversationResponse)
	err := c.cc.Invoke(ctx, IOService_LoadConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iOServiceClient) DeleteConversation(ctx context.Context, in *DeleteConversationRequest, opts ...grpc.CallOption) (*DeleteConversationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteConversationResponse)
	err := c.cc.Invoke(ctx, IOService_DeleteConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iOServiceClient) ListAIConfigs(ctx context.Context, in *ListAIConfigsRequest, opts ...grpc.CallOption) (*ListAIConfigsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAIConfigsResponse)
	err := c.cc.Invoke(ctx, IOService_ListAIConfigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iOServiceClient) SwitchAIConfig(ctx context.Context, in *SwitchAIConfigRequest, opts ...grpc.CallOption) (*SwitchAIConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwitchAIConfigResponse)
	err := c.cc.Invoke(ctx, IOService_SwitchAIConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iOServiceClient) ListProviders(ctx context.Context, in *ListProvidersRequest, opts ...grpc.CallOption) (*ListProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProvidersResponse)
	err := c.cc.Invoke(ctx, IOService_ListProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IOServiceServer is the server API for IOService service.
// All implementations must embed UnimplementedIOServiceServer
// for forward compatibility.
//
// The main service
type IOServiceServer interface {
	// Send a message and get AI response
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	// Send message to backend only for storage
	StoreMessage(context.Context, *StoreMessageRequest) (*StoreMessageResponse, error)
	// Conversation management
	ListConversations(context.Context, *ListConversationsRequest) (*ListConversationsResponse, error)
	LoadConversation(context.Context, *LoadConversationRequest) (*LoadConversationResponse, error)
	DeleteConversation(context.Context, *DeleteConversationRequest) (*DeleteConversationResponse, error)
	// AI Config management
	ListAIConfigs(context.Context, *ListAIConfigsRequest) (*ListAIConfigsResponse, error)
	SwitchAIConfig(context.Context, *SwitchAIConfigRequest) (*SwitchAIConfigResponse, error)
	// Provider management
	ListProviders(context.Context, *ListProvidersRequest) (*ListProvidersResponse, error)
	mustEmbedUnimplementedIOServiceServer()
}

// UnimplementedIOServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIOServiceServer struct{}

func (UnimplementedIOServiceServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedIOServiceServer) StoreMessage(context.Context, *StoreMessageRequest) (*StoreMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreMessage not implemented")
}
func (UnimplementedIOServiceServer) ListConversations(context.Context, *ListConversationsRequest) (*ListConversationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConversations not implemented")
}
func (UnimplementedIOServiceServer) LoadConversation(context.Context, *LoadConversationRequest) (*LoadConversationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadConversation not implemented")
}
func (UnimplementedIOServiceServer) DeleteConversation(context.Context, *DeleteConversationRequest) (*DeleteConversationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteConversation not implemented")
}
func (UnimplementedIOServiceServer) ListAIConfigs(context.Context, *ListAIConfigsRequest) (*ListAIConfigsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAIConfigs not implemented")
}
func (UnimplementedIOServiceServer) SwitchAIConfig(context.Context, *SwitchAIConfigRequest) (*SwitchAIConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SwitchAIConfig not implemented")
}
func (UnimplementedIOServiceServer) ListProviders(context.Context, *ListProvidersRequest) (*ListProvidersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProviders not implemented")
}
func (UnimplementedIOServiceServer) mustEmbedUnimplementedIOServiceServer() {}
func (UnimplementedIOServiceServer) testEmbeddedByValue()                   {}

// UnsafeIOServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IOServiceServer will
// result in compilation errors.
type UnsafeIOServiceServer interface {
	mustEmbedUnimplementedIOServiceServer()
}

func RegisterIOServiceServer(s grpc.ServiceRegistrar, srv IOServiceServer) {
	// If the following call panics, it indicates UnimplementedIOServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IOService_ServiceDesc, srv)
}

func _IOService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IOServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IOService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IOServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IOService_StoreMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IOServiceServer).StoreMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IOService_StoreMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IOServiceServer).StoreMessage(ctx, req.(*StoreMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IOService_ListConversations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConversationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IOServiceServer).ListConversations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IOService_ListConversations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IOServiceServer).ListConversations(ctx, req.(*ListConversationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IOService_LoadConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IOServiceServer).LoadConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IOService_LoadConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IOServiceServer).LoadConversation(ctx, req.(*LoadConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IOService_DeleteConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IOServiceServer).DeleteConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IOService_DeleteConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IOServiceServer).DeleteConversation(ctx, req.(*DeleteConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IOService_ListAIConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAIConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IOServiceServer).ListAIConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IOService_ListAIConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IOServiceServer).ListAIConfigs(ctx, req.(*ListAIConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IOService_SwitchAIConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwitchAIConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IOServiceServer).SwitchAIConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IOService_SwitchAIConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IOServiceServer).SwitchAIConfig(ctx, req.(*SwitchAIConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IOService_ListProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IOServiceServer).ListProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IOService_ListProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IOServiceServer).ListProviders(ctx, req.(*ListProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IOService_ServiceDesc is the grpc.ServiceDesc for IOService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IOService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "io.IOService",
	HandlerType: (*IOServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _IOService_SendMessage_Handler,
		},
		{
			MethodName: "StoreMessage",
			Handler:    _IOService_StoreMessage_Handler,
		},
		{
			MethodName: "ListConversations",
			Handler:    _IOService_ListConversations_Handler,
		},
		{
			MethodName: "LoadConversation",
			Handler:    _IOService_LoadConversation_Handler,
		},
		{
			MethodName: "DeleteConversation",
			Handler:    _IOService_DeleteConversation_Handler,
		},
		{
			MethodName: "ListAIConfigs",
			Handler:    _IOService_ListAIConfigs_Handler,
		},
		{
			MethodName: "SwitchAIConfig",
			Handler:    _IOService_SwitchAIConfig_Handler,
		},
		{
			MethodName: "ListProviders",
			Handler:    _IOService_ListProviders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "io.proto",
}
